name: Build UU-status (CSV + Details + Page)

on:
  schedule:
    - cron: "27 1 * * *"   # daglig 01:27 UTC (02:27/03:27 i Norge)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0          # <-- viktig for å kunne hente forrige latest.json fra git

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build UU-status CSV + details
        run: |
          python scrape_uustatus.py

      - name: Copy files to docs (for GitHub Pages)
        run: |
          mkdir -p docs
          cp uu-status.csv docs/uu-status.csv
          cp uu-status-details.json docs/uu-status-details.json

      - name: Ensure archive folders & seed files
        run: |
          mkdir -p docs/data/uustatus/snapshots_by_updated
          mkdir -p docs/data/uustatus/snapshots
          mkdir -p docs/data/uustatus/logs
          [ -f docs/data/uustatus/latest.json ] || echo '{ "urls": [] }' > docs/data/uustatus/latest.json
          [ -f docs/data/uustatus/logs/changes.jsonl ] || : > docs/data/uustatus/logs/changes.jsonl

- name: Build archive (diff & event snapshots)
  run: |
    python build_uu_archive.py
  env:
    BASELINE_REF: "HEAD~1"   # sammenlign mot forrige commit
    DEBUG_URL_CONTAINS: "veldedig-eller-allmennyttig"  # unik bit av URLen du endret



      - name: Commit updated CSV, details and page (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage endringer
          git add uu-status.csv uu-status-details.json
          git add docs/uu-status.csv docs/uu-status-details.json docs/uu-status.html docs/uu-arkiv.html
          git add docs/data/uustatus/latest.json docs/data/uustatus/logs/changes.jsonl
          git add docs/data/uustatus/snapshots_by_updated/*.json || true   # kan være ingen

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update UU-status + archive (csv, details, page, snapshots, changes)"
            # Rebase på siste main for å unngå 'fetch first'
            git pull --rebase
            git push
          fi
