
name: Build UU-status page

on:
  schedule:
    - cron: "12 4 * * 1"   # hver mandag 04:12 UTC
  workflow_dispatch: {}     # lar deg kjøre manuelt fra Actions

permissions:
  contents: write           # trengs for å pushe endringer tilbake til repoet

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Build UU-status page
        run: |
          python scrape_uustatus.py

      - name: Commit updated page (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uu-status/index.html
          git diff --staged --quiet || git commit -m "Update UU-status page"
          git push
