0name: Build UU-status (CSV + Details + Page)

on:
  schedule:
    - cron: "27 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build UU-status CSV + details
        run: |
          python scrape_uustatus.py

      - name: Copy files to docs (for GitHub Pages)
        run: |
          mkdir -p docs
          cp uu-status.csv docs/uu-status.csv
          cp uu-status-details.json docs/uu-status-details.json

      - name: Ensure archive folders & seed files
        run: |
          mkdir -p docs/data/uustatus/snapshots_by_updated
          mkdir -p docs/data/uustatus/snapshots
          mkdir -p docs/data/uustatus/logs
          [ -f docs/data/uustatus/latest.json ] || echo '{ "urls": [] }' > docs/data/uustatus/latest.json
          [ -f docs/data/uustatus/logs/changes.jsonl ] || : > docs/data/uustatus/logs/changes.jsonl

      # --- DEBUG A: list alle 'A-meldingen' i dagens details.json
      - name: Debug scan: list 'A-meldingen' entries in current details.json
        run: |
          python - <<'PY'
          import json
          from pathlib import Path

          def extract_codes(obj):
              for k in ["nonConformities","violations","wcag","issues","problems"]:
                  if k in obj:
                      v = obj[k]
                      if isinstance(v, str):
                          return [s.strip() for s in v.split(";") if s.strip()]
                      if isinstance(v, list):
                          out=[]
                          for it in v:
                              if isinstance(it, str):
                                  out.append(it.strip())
                              elif isinstance(it, dict):
                                  for kk in ["code","wcag","criterion","id","wcagId","wcag_id"]:
                                      if it.get(kk):
                                          out.append(str(it[kk]).strip()); break
                          return sorted(set(out))
              return []

          data = json.loads(Path("docs/uu-status-details.json").read_text(encoding="utf-8"))
          rows = data.get("urls") if isinstance(data, dict) else data
          hits = []
          for r in rows:
              title = (r.get("title") or r.get("name") or "").lower()
              url = (r.get("url") or r.get("href") or "").lower()
              if "a-meldingen" in title:
                  hits.append((title, url, extract_codes(r), r.get("totalNonConformities"), r.get("updatedAt")))
          print("Found A-meldingen entries:", len(hits))
          for t,u,c,tot,ua in hits:
              print(" - TITLE:", t)
              print("   URL:  ", u)
              print("   total:", tot if tot is not None else len(c), "codes:", c, "updatedAt:", ua)
          PY

      # --- DEBUG B: finn alt som matcher 'avstemm' i tittel eller URL
      - name: Debug scan: anything matching 'avstemm' in current details.json
        run: |
          python - <<'PY'
          import json
          from pathlib import Path
          KEY = "avstemm"
          def extract_codes(obj):
              for k in ["nonConformities","violations","wcag","issues","problems"]:
                  if k in obj:
                      v = obj[k]
                      if isinstance(v, str):
                          return [s.strip() for s in v.split(";") if s.strip()]
                      if isinstance(v, list):
                          out=[]
                          for it in v:
                              if isinstance(it, str):
                                  out.append(it.strip())
                              elif isinstance(it, dict):
                                  for kk in ["code","wcag","criterion","id","wcagId","wcag_id"]:
                                      if it.get(kk):
                                          out.append(str(it[kk]).strip()); break
                          return sorted(set(out))
              return []
          data = json.loads(Path("docs/uu-status-details.json").read_text(encoding="utf-8"))
          rows = data.get("urls") if isinstance(data, dict) else data
          found = []
          for r in rows:
              title = (r.get("title") or r.get("name") or "")
              url = (r.get("url") or r.get("href") or "")
              if KEY in title.lower() or KEY in url.lower():
                  c = extract_codes(r)
                  tot = r.get("totalNonConformities")
                  print("MATCH title:", title)
                  print("      url  :", url)
                  print("      total:", tot if tot is not None else len(c), "codes:", c, "updatedAt:", r.get("updatedAt"))
                  found.append(1)
          print("Matches:", len(found))
          PY

      - name: Sanity check of archive script
        run: |
          grep -n "AUTO_BACKTRACK" build_uu_archive.py || (echo "ERROR: build_uu_archive.py mangler AUTO_BACKTRACK-støtte" && exit 1)

      - name: Build archive (diff & event snapshots)
        env:
          AUTO_BACKTRACK: "1"
          MAX_BACKTRACK: "20"
          DEBUG_URL_CONTAINS: "avstemm"     # matcher både i tittel og url i nytt script
        run: |
          python build_uu_archive.py

      - name: Commit updated CSV, details and page (if changed)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uu-status.csv uu-status-details.json || true
          git add -A docs
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update UU-status + archive (csv, details, page, snapshots, changes)"
            git pull --rebase
            git push
          fi
