name: Build UU-status (CSV + Details + Page)

on:
  schedule:
    - cron: "27 1 * * *"   # daglig 01:27 UTC (02:27/03:27 i Norge)
  workflow_dispatch:

permissions:
  contents: write           # må ha write for å pushe med GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build UU-status CSV + details
        run: |
          python scrape_uustatus.py

      - name: Copy files to docs (for GitHub Pages)
        run: |
          mkdir -p docs
          cp uu-status.csv docs/uu-status.csv
          cp uu-status-details.json docs/uu-status-details.json

      - name: Commit updated CSV, details and page (if changed)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uu-status.csv uu-status-details.json docs/uu-status.csv docs/uu-status-details.json docs/uu-status.html
          git diff --staged --quiet || git commit -m "Update UU-status (csv + details + page)"
          git push
